package nil.ed.test.tool;

public class EnumGenerator {
    public static void main(String[] args) {
        String enumStr = "UNKNOWN_EVENT,START_EVENT_V3,QUERY_EVENT,STOP_EVENT,ROTATE_EVENT,INTVAR_EVENT,LOAD_EVENT,SLAVE_EVENT,CREATE_FILE_EVENT,APPEND_BLOCK_EVENT,EXEC_LOAD_EVENT,DELETE_FILE_EVENT,NEW_LOAD_EVENT,RAND_EVENT,USER_VAR_EVENT,FORMAT_DESCRIPTION_EVENT,XID_EVENT,BEGIN_LOAD_QUERY_EVENT,EXECUTE_LOAD_QUERY_EVENT,TABLE_MAP_EVENT,WRITE_ROWS_EVENTv0,UPDATE_ROWS_EVENTv0,DELETE_ROWS_EVENTv0,WRITE_ROWS_EVENTv1,UPDATE_ROWS_EVENTv1,DELETE_ROWS_EVENTv1,INCIDENT_EVENT,HEARTBEAT_EVENT,IGNORABLE_EVENT,ROWS_QUERY_EVENT,WRITE_ROWS_EVENTv2,UPDATE_ROWS_EVENTv2,DELETE_ROWS_EVENTv2,GTID_EVENT,ANONYMOUS_GTID_EVENT,PREVIOUS_GTIDS_EVENT";

        String[] parts = enumStr.split("\\s*,\\s*");
        int code = 0;
        for (String part : parts) {
            System.out.println(String.format("%s(%d, %s),", part, code, "\"\""));
            code += 1;
        }
    }
}
