/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class nil_ed_test_jni_HelloWorld */

#ifndef _Included_nil_ed_test_jni_HelloWorld
#define _Included_nil_ed_test_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nil_ed_test_jni_HelloWorld
 * Method:    hello
 * Signature: (Ljava/time/LocalDateTime;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nil_ed_test_jni_HelloWorld_hello
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
