/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nil_ed_test_jni_HelloWorld2 */

#ifndef _Included_nil_ed_test_jni_HelloWorld2
#define _Included_nil_ed_test_jni_HelloWorld2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nil_ed_test_jni_HelloWorld2
 * Method:    hello
 * Signature: (Ljava/time/LocalDateTime;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nil_ed_test_jni_HelloWorld2_hello
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
